In [1]:
from chess_board.base_board import ChessBoard

In [2]:
cb = ChessBoard(6, 6, 3)

In [3]:
print(cb.move(1, 2, 3))
print(cb.move(2, 2, 4))
print(cb.move(1, 2, 5))

(0, None)
(0, None)
(0, None)


In [4]:
cb.board

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
print(cb.move(2, 3, 4))
print(cb.move(1, 4, 5))
print(cb.move(2, 3, 1))
print(cb.move(1, 3, 5))

(0, None)
(0, None)
(0, None)
(1, <GAME_PLAYER.PLAYER_ONE: 1>)


In [6]:
cb.board

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 1],
       [0, 2, 0, 0, 2, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [7]:
print(cb.move(1, 1, 1))

2021-08-11 23:40:45.848 | ERROR    | chess_board.base_board:move:44 - Game is not reset !


(-1, None)


In [1]:
from ai.net import Net
import torch
import numpy as np

net = Net(5, 5)

a = np.ones((2, 3, 5, 5))
a = torch.Tensor(a)
act, value = net(a)

In [2]:
act.shape

torch.Size([2, 5, 5])

In [3]:
act

tensor([[[0.0401, 0.0401, 0.0401, 0.0400, 0.0399],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398]],

        [[0.0401, 0.0401, 0.0401, 0.0400, 0.0399],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398]]], grad_fn=<ViewBackward>)

In [4]:
torch.sum(act, dim=-1)

tensor([[0.2002, 0.2000, 0.1999, 0.1999, 0.2000],
        [0.2002, 0.2000, 0.1999, 0.1999, 0.2000]], grad_fn=<SumBackward1>)

In [7]:
value.shape

torch.Size([2, 1])

In [6]:
a = np.ones((2, 3))
a = torch.Tensor(a)
softmax = torch.nn.Softmax(dim=2)
softmax(a)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [6]:
a=1
b=2
c=3
a, b, c = c, b, a

In [7]:
a

3

In [8]:
b

2

In [9]:
c

1