In [1]:
from chess_board.base_board import ChessBoard

In [2]:
cb = ChessBoard(6, 6, 3)

In [3]:
print(cb.move(1, 2, 3))
print(cb.move(2, 2, 4))
print(cb.move(1, 2, 5))

(0, None)
(0, None)
(0, None)


In [4]:
cb.board

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
print(cb.move(2, 3, 4))
print(cb.move(1, 4, 5))
print(cb.move(2, 3, 1))
print(cb.move(1, 3, 5))

(0, None)
(0, None)
(0, None)
(1, <GAME_PLAYER.PLAYER_ONE: 1>)


In [6]:
cb.board

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 1],
       [0, 2, 0, 0, 2, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [7]:
print(cb.move(1, 1, 1))

2021-08-11 23:40:45.848 | ERROR    | chess_board.base_board:move:44 - Game is not reset !


(-1, None)


In [1]:
from ai.net import Net
import torch
import numpy as np

net = Net(5, 5)

a = np.ones((2, 3, 5, 5))
a = torch.Tensor(a)
act, value = net(a)

In [2]:
act.shape

torch.Size([2, 5, 5])

In [3]:
act

tensor([[[0.0401, 0.0401, 0.0401, 0.0400, 0.0399],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398]],

        [[0.0401, 0.0401, 0.0401, 0.0400, 0.0399],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0397],
         [0.0401, 0.0401, 0.0401, 0.0400, 0.0398]]], grad_fn=<ViewBackward>)

In [4]:
torch.sum(act, dim=-1)

tensor([[0.2002, 0.2000, 0.1999, 0.1999, 0.2000],
        [0.2002, 0.2000, 0.1999, 0.1999, 0.2000]], grad_fn=<SumBackward1>)

In [7]:
value.shape

torch.Size([2, 1])

In [6]:
a = np.ones((2, 3))
a = torch.Tensor(a)
softmax = torch.nn.Softmax(dim=2)
softmax(a)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [6]:
a=1
b=2
c=3
a, b, c = c, b, a

In [7]:
a

3

In [8]:
b

2

In [9]:
c

1

In [9]:
import numpy as np

a = np.array([0,0,0,0, 0])

In [10]:
a[5%2-1::2]=1

In [11]:
a

array([1, 0, 1, 0, 1])

In [2]:
import numpy as np

a = np.array([1,2])
np.expand_dims(a, axis=-1)

array([[1],
       [2]])

In [1]:
import torch
import numpy as np


q = np.ones((5, 10, 9))
k = np.ones((5,  9, 5))

q = torch.Tensor(q)
k = torch.Tensor(k)
torch.bmm(q, k).shape

torch.Size([5, 10, 5])

In [1]:
from user.transformer.attention import Attention
from user.transformer.net import Transformer
import torch
import numpy as np


# model = Attention(10, 5, 15)
model = Transformer(5, 10, 15)

In [2]:
# data
q = np.ones((16, 10, 15, 15))
k = np.ones((16, 5, 15, 15))
v = np.ones((16, 5, 15, 15))

q = torch.Tensor(q)
k = torch.Tensor(k)
v = torch.Tensor(v)

In [4]:
model(q, k, v)

tensor([[[9.7616e-17, 1.8235e-14, 5.3336e-18,  ..., 1.4651e-17,
          1.8178e-17, 7.6781e-17],
         [7.4481e-14, 1.5173e-14, 1.2948e-15,  ..., 2.9989e-15,
          1.1214e-17, 1.3460e-14],
         [9.1767e-12, 9.8639e-10, 7.9543e-15,  ..., 1.8823e-12,
          1.0294e-15, 1.4488e-10],
         ...,
         [3.6709e-16, 1.9122e-14, 3.0732e-18,  ..., 4.5028e-18,
          1.5212e-16, 1.2825e-17],
         [1.2434e-13, 3.5618e-14, 1.6428e-15,  ..., 1.1274e-15,
          9.9224e-18, 1.7940e-14],
         [2.8535e-14, 2.2956e-13, 2.9409e-15,  ..., 2.1050e-14,
          2.9882e-17, 1.8138e-13]],

        [[1.7234e-14, 5.3244e-14, 6.9127e-15,  ..., 3.3984e-12,
          6.5372e-14, 1.1584e-10],
         [5.5674e-13, 6.1609e-13, 2.0778e-12,  ..., 3.0760e-09,
          6.0966e-13, 1.9363e-06],
         [6.3013e-11, 1.4066e-11, 2.0918e-12,  ..., 1.0111e-05,
          4.4334e-10, 8.3104e-01],
         ...,
         [6.0462e-15, 1.2253e-13, 6.2613e-15,  ..., 8.6277e-13,
          1.063

(0, 1, 2)

In [82]:
import torch

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a = torch.Tensor(a)

In [85]:
b = [0,1]
c = [2,2]
a[b,c]

tensor([3., 8.])

In [84]:
torch.index_select(a, dim=-1, index=b)

IndexError: index_select(): Index is supposed to be a vector

In [95]:
import torch
from torch import Tensor

a = np.array([[0.9],[0.1]])
label = np.array([[1],[0]])

a = Tensor(a)
label = Tensor(label)

torch.sum(-label * torch.log(a) -(1-label) * torch.log(1-a))

tensor(0.2107)

In [2]:
import math
label = 0
pred = 0.5

-(1-label + 0.001)*math.log(pred) - label*math.log(pred + 0.001)

0.6938403277405052

In [3]:
-(1-label + 0.001)*math.log(pred)

0.6938403277405052

In [4]:
label*math.log(pred + 0.001)

-0.0

In [2]:
import torch

a = torch.randn(2,2)
a = ((a*3)/ (a-1))
a.requires_grad_(True)
b = (a * a).sum()
b.backward()
print(b.grad)
print(a.grad)

None
tensor([[ -34.0340,    1.9998],
        [-626.7603,    2.4360]])


<ipython-input-2-ae65f709fbcd>:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print(b.grad)


In [7]:
import numpy as np

a = np.array([[4,3], [0,1]])

In [8]:
a

array([[4, 3],
       [0, 1]])

In [9]:
a[(0,1), (0,1)]

array([4, 1])

In [11]:
win_step = [(7, 9), (3, 5)]
print("debug:", [x[0] for x in win_step])

debug: [7, 3]


In [14]:
import numpy as np


a = np.random.randn()

In [15]:
a

0.5315617507761129

In [29]:
import random
from collections import defaultdict


dic = defaultdict(int)
for _ in range(1000000):
    num = random.triangular(0,1)
    dic[int(num * 10)] += 1
sum_ = sum(dic.values())
dic = {key: dic[key] / sum_ for key in dic}
dic

{5: 0.17993,
 6: 0.140281,
 4: 0.179378,
 7: 0.099698,
 1: 0.060196,
 8: 0.059716,
 2: 0.100202,
 0: 0.019889,
 3: 0.140415,
 9: 0.020295}

In [36]:
import random
from collections import defaultdict


dic = defaultdict(int)
for _ in range(1000000):
    num = random.betavariate(10,10)
    dic[int(num * 10)] += 1
sum_ = sum(dic.values())
dic = {key: dic[key] / sum_ for key in dic}
dic

{4: 0.314233,
 5: 0.31313,
 3: 0.153408,
 7: 0.031065,
 2: 0.031242,
 6: 0.15364,
 1: 0.001587,
 8: 0.001685,
 0: 4e-06,
 9: 6e-06}

In [37]:
print("java script execute failed, msg: null,\tstackTrace info: \n\tcom.pdd.search.xcheck.TuneTaskClass.accumulatedMetric(TuneTaskClass.java:152)\n\tcom.pdd.search.xcheck.TuneTaskClass.process(TuneTaskClass.java:694)\n\tsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tjava.lang.reflect.Method.invoke(Method.java:498)\n\tcom.pdd.search.xcheck.service.tuning.script.JavaDynamicExecutor.run(JavaDynamicExecutor.java:33)\n\tcom.pdd.search.xcheck.service.tuning.DataProcessor.scriptProcess(DataProcessor.java:48)\n\tcom.pdd.search.xcheck.tuningTask.TuningTaskExecutor$TaskExecuteUnit.run(TuningTaskExecutor.java:159)\n\tjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tjava.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tcom.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:52)\n\tjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tjava.lang.Thread.run(Thread.java:748)\n",
      )

java script execute failed, msg: null,	stackTrace info: 
	com.pdd.search.xcheck.TuneTaskClass.accumulatedMetric(TuneTaskClass.java:152)
	com.pdd.search.xcheck.TuneTaskClass.process(TuneTaskClass.java:694)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	com.pdd.search.xcheck.service.tuning.script.JavaDynamicExecutor.run(JavaDynamicExecutor.java:33)
	com.pdd.search.xcheck.service.tuning.DataProcessor.scriptProcess(DataProcessor.java:48)
	com.pdd.search.xcheck.tuningTask.TuningTaskExecutor$TaskExecuteUnit.run(TuningTaskExecutor.java:159)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:52)
	java.util.concurrent.ThreadPoolExecutor.run

In [39]:
print("java script execute failed, msg: null,\tstackTrace info: \n\tcom.pdd.search.xcheck.TuneTaskClass.accumulatedMetric(TuneTaskClass.java:433)\n\tcom.pdd.search.xcheck.TuneTaskClass$UCBBandit.updateOneExp(TuneTaskClass.java:308)\n\tcom.pdd.search.xcheck.TuneTaskClass$UCBBandit.update(TuneTaskClass.java:244)\n\tcom.pdd.search.xcheck.TuneTaskClass.process(TuneTaskClass.java:117)\n\tsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tjava.lang.reflect.Method.invoke(Method.java:498)\n\tcom.pdd.search.xcheck.service.tuning.script.JavaDynamicExecutor.run(JavaDynamicExecutor.java:33)\n\tcom.pdd.search.xcheck.controller.http.tuning.TaskTestController.executeScript(TaskTestController.java:94)\n\tcom.pdd.search.xcheck.controller.http.tuning.TaskTestController$$FastClassBySpringCGLIB$$87487215.invoke(<generated>)\n\torg.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)\n\torg.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)\n\torg.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)\n\torg.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)\n\torg.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)\n\torg.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)\n\torg.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\torg.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)\n\tcom.pdd.search.xcheck.controller.http.tuning.TaskTestController$$EnhancerBySpringCGLIB$$dd0a6c.executeScript(<generated>)\n\tsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tjava.lang.reflect.Method.invoke(Method.java:498)\n\torg.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n\torg.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)\n\torg.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)\n\torg.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)\n\torg.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)\n\torg.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n\torg.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)\n\torg.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)\n\torg.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)\n\torg.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:707)\n\torg.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\n\tjavax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tcom.dianping.cat.servlet.CatFilter.logTransaction(CatFilter.java:273)\n\tcom.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:92)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)\n\torg.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tcom.pdd.iris.spring.filter.IrisWebFilter.doFilter(IrisWebFilter.java:43)\n\torg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\torg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\torg.apache.catalina.core.StandardWrapperValve.invoke$original$PP8jkxf7(StandardWrapperValve.java:198)\n\torg.apache.catalina.core.StandardWrapperValve.invoke$original$PP8jkxf7$accessor$GDToxtH7(StandardWrapperValve.java)\n\torg.apache.catalina.core.StandardWrapperValve$auxiliary$Sli1pAQ0.call(Unknown Source)\n\tcom.pdd.service.ptracer.boot.api.injector.enhance.InstanceMethodEnhancer.enhance(InstanceMethodEnhancer.java:61)\n\torg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java)\n\torg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\torg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)\n\torg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\torg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\n\torg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\torg.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)\n\torg.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)\n\torg.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\torg.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)\n\torg.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)\n\torg.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tcom.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:52)\n\tjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\torg.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tjava.lang.Thread.run(Thread.java:748)\n",
 )

java script execute failed, msg: null,	stackTrace info: 
	com.pdd.search.xcheck.TuneTaskClass.accumulatedMetric(TuneTaskClass.java:433)
	com.pdd.search.xcheck.TuneTaskClass$UCBBandit.updateOneExp(TuneTaskClass.java:308)
	com.pdd.search.xcheck.TuneTaskClass$UCBBandit.update(TuneTaskClass.java:244)
	com.pdd.search.xcheck.TuneTaskClass.process(TuneTaskClass.java:117)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	com.pdd.search.xcheck.service.tuning.script.JavaDynamicExecutor.run(JavaDynamicExecutor.java:33)
	com.pdd.search.xcheck.controller.http.tuning.TaskTestController.executeScript(TaskTestController.java:94)
	com.pdd.search.xcheck.controller.http.tuning.TaskTestController$$FastClassBySpringCGLIB$$87487215.invoke(<generated>)
	org.springframework.cglib.proxy